mixin AppLocale {
  static const List<String> titles = [
    'title',
    'title1',
    'title2',
    'title3',
    'title4',
    'title5',
    'title6',
    'title7',
  ];
  static const List<String> info = [
    'info',
    'info1',
    'info2',
    'info3',
    'info4',
    'info5',
    'info6',
    'info7',
    'info8',
    'info9',
    'info10',
    'info11',
    'info12',
    'info13',
    'info14',
    'info15'
  ];
  static const List<String> args = [
    'args',
    'args1',
    'args2',
    'args3',
    'args4',
    'args5',
    'args6',
    'args7',
    'args8',
    'args9',
    'args10',
    'args11',
    'args12',
    'args13',
    'args14',
    'args15',
    'args16',
    'args17',
    'args18',
    'args19',
    'args20',
    'args21',
    'args22',
  ];

  static Map<String, dynamic> EN = {
    titles[0]: 'Fire Alert',
    titles[1]: 'Event',
    titles[2]: 'History',
    titles[3]: 'Report',
    titles[4]: 'Device',
    titles[5]: 'Setting',
    titles[6]: 'Parameter settings',
    titles[7]: 'Details',
    info[0]: 'No event data',
    info[1]: 'No data',
    info[2]: 'Device abnormal',
    info[3]: 'Normal',
    info[4]: ' Please enter text',
    info[5]: 'Modify',
    info[6]: 'Sensor abnormal',
    info[7]: 'Login',
    info[8]: 'Logout',
    info[9]: 'User name ',
    info[10]: 'Password ',
    info[11]: 'Fire',
    info[12]: 'Person trapped',
    info[13]: 'Type',
    info[14]: 'Current location',
    info[15]: 'Additional description',
    args[0]: 'Temperature parameter: ',
    args[1]: 'Smoke parameter: ',
    args[2]: 'Location: ',
    args[3]: 'Sensor ID: ',
    args[4]: 'Status: ',
    args[5]: 'Last response: ',
    args[6]: 'IP Address: ',
    args[7]: '• Device number: ',
    args[8]: '• Smoke sensor: ',
    args[9]: '• Temperature sensor: ',
    args[10]: '• Name setting: ',
    args[11]: '• Group setting: ',
    args[12]: '• Device enable: ',
    args[13]: 'Smoke threshold: ',
    args[14]: 'Smoke sensitivity: ',
    args[15]: 'Temperature threshold: ',
    args[16]: 'Heat sensitivity: ',
    args[17]: 'Recording duration: ',
    args[18]: 'Time: ',
    args[19]: 'Event level: ',
    args[20]: 'Update time: ',
    args[21]: 'User name',
    args[22]: 'Alert: ',
  };

  static Map<String, dynamic> ZH_TW = {
    titles[0]: '火燒報哩災',
    titles[1]: '事件',
    titles[2]: '歷史紀錄',
    titles[3]: '通報',
    titles[4]: '設備',
    titles[5]: '設定',
    titles[6]: '參數設定',
    titles[7]: '詳細資料',
    info[0]: '無事件資料',
    info[1]: '無資料',
    info[2]: '設備異常',
    info[3]: '正常',
    info[4]: ' 請輸入文字',
    info[5]: '修改',
    info[6]: '感測異常',
    info[7]: '登入',
    info[8]: '登出',
    info[9]: '使用者名稱 ',
    info[10]: '密碼 ',
    info[11]: '火災',
    info[12]: '人員受困',
    info[13]: '類型',
    info[14]: '目前定位點',
    info[15]: '額外描述',
    args[0]: '溫度參數: ',
    args[1]: '煙霧參數: ',
    args[2]: '位置: ',
    args[3]: '感測器ID: ',
    args[4]: '狀態: ',
    args[5]: '上次回應: ',
    args[6]: 'IP 地址: ',
    args[7]: '• 設備編號: ',
    args[8]: '• 感測煙霧: ',
    args[9]: '• 感測溫度: ',
    args[10]: '• 名稱設定: ',
    args[11]: '• 群組設定: ',
    args[12]: '• 設備啟用: ',
    args[13]: '煙霧閥值: ',
    args[14]: '煙敏感度: ',
    args[15]: '溫度閥值: ',
    args[16]: '熱敏感度: ',
    args[17]: '錄影時長: ',
    args[18]: '時間:',
    args[19]: '事件等級:',
    args[20]: '更新時間:',
    args[21]: '使用者名稱',
    args[22]: '警報:',
  };
}
